volumes:
  vol-database:
  vol-images:
  vol-client:

services:
  router:
    extends:
      file: docker-compose.shared.yml
      service: router
    ports:
      - "${APP_PORT}:443"
    restart: always

  server:
    extends:
      file: docker-compose.shared.yml
      service: server

  client:
    extends:
      file: docker-compose.shared.yml
      service: client

  og-injector:
    extends:
      file: docker-compose.shared.yml
      service: og-injector

  db:
    extends:
      file: docker-compose.shared.yml
      service: db
