version: "3.9"

volumes:
  vol-database:
  vol-images:
  vol-client:

services:
  router:
    extends:
      file: docker-compose.shared.yml
      service: router

  server:
    extends:
      file: docker-compose.shared.yml
      service: server
    volumes:
      - ./server:/opt/server:rw
      - vol-images:/opt/images:rw
    environment:
      CLIENT_URL: "${CLIENT_URL}"

  client:
    extends:
      file: docker-compose.shared.yml
      service: client
    volumes:
      - ./client:/opt/client:rw
      - ./.certs:/opt/ssl:ro
      - vol-client:/opt/client/build:rw
    environment:
      HTTPS: true
      SSL_CRT_FILE: /opt/ssl/current.crt
      SSL_KEY_FILE: /opt/ssl/current.key
    command: yarn start
    ports:
      - "${CLIENT_PORT}:3000"

  og-injector:
    extends:
      file: docker-compose.shared.yml
      service: og-injector
    volumes:
      - ./og-injector:/opt/og-injector:rw
      - vol-client:/opt/client:ro
    command: yarn watch

  db:
    extends:
      file: docker-compose.shared.yml
      service: db
    ports:
      - "${DB_PORT}:5432"
