services:
  router:
    extends:
      file: docker-compose.production.yml
      service: router
  server:
    extends:
      file: docker-compose.production.yml
      service: server
    volumes:
      - ./packages/server:/opt/server:rw
      - ./.volumes/images:/opt/images:rw
    environment:
      RAILS_ENV: "${APP_ENV}"
      CLIENT_URL: "${DEV_CLIENT_URL}"
      SERVER_URL: "${DEV_ROUTER_URL}/api"
      IMAGES_URL: "${DEV_ROUTER_URL}/images"
    ports:
      - "${DEV_SERVER_PORT}:3000"

  client:
    extends:
      file: docker-compose.production.yml
      service: client
    volumes:
      - ./packages/website/src:/opt/app/src:rw
      - "${SSL_CRT}:/opt/ssl/current.crt:ro"
      - "${SSL_KEY}:/opt/ssl/current.key:ro"
    environment:
      NODE_ENV: "${APP_ENV}"
      VITE_ENV: "${APP_ENV}"
      PORT: 3000
      HTTPS: true
      SSL_CRT_FILE: /opt/ssl/current.crt
      SSL_KEY_FILE: /opt/ssl/current.key
      VITE_SERVER_URL: "${DEV_ROUTER_URL}/api"
    command: yarn dev
    ports:
      - "${DEV_CLIENT_PORT}:3000"

  og-injector:
    extends:
      file: docker-compose.production.yml
      service: og-injector
    ports:
      - "${DEV_INJECTOR_PORT}:3000"
    volumes:
      - ./packages/og-injector/target/debug/og-injector:/usr/bin/og-injector:ro
      - ./.volumes/client:/opt/client:ro

  db:
    extends:
      file: docker-compose.production.yml
      service: db
    ports:
      - "${DEV_DB_PORT}:5432"
