version: "3.9"

services:
  nginx:
    image: nginx:stable
    ports:
      - 8080:443
    depends_on:
      - server
    volumes:
      - ./.volumes/router/conf.d:/etc/nginx/conf.d
      - ./.volumes/router/ssl:/opt/ssl
      - ./.volumes/images:/opt/images
      - ./client/build:/opt/client

  server:
    image: ruby:3.1.2
    build: ./server
    working_dir: /opt/server
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./server:/opt/server
      - ./.volumes/images:/opt/images
    depends_on:
      - db
    environment:
      SERVER_URL: "${SERVER_URL}"
      DB_HOST: db #Override .env and use the docker network
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      IMG_SERVER_URL: "${IMG_SERVER_URL}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      IMAGES_DIR: "/opt/images"

  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
