version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  image-server:
    image: halverneus/static-file-server
    ports:
      - 3002:8080
    volumes:
      - ./data/images:/web
