version: "3.9"

volumes:
  vol-database:
  vol-images:
  vol-client:

services:
  router:
    extends:
      file: docker-compose.shared.yml
      service: router
    volumes:
      - ./router/ssl/prod:/opt/ssl:ro
      - vol-images:/opt/images:ro
      - vol-client:/opt/client:ro
    ports:
      - "${APP_PORT}:443"
    restart: always

  server:
    extends:
      file: docker-compose.shared.yml
      service: server
    restart: always

  client:
    extends:
      file: docker-compose.shared.yml
      service: client

  og-injector:
    extends:
      file: docker-compose.shared.yml
      service: og-injector
    restart: always

  db:
    extends:
      file: docker-compose.shared.yml
      service: db
    restart: always
