version: "3.9"

services:
  nginx:
    image: nginx:stable
    depends_on:
      - server
      - client
    volumes:
      - ./.volumes/router/conf.d:/etc/nginxconf.d
      - ./.volumes/ssl:/opt/ssl
      - ./.volumes/images:/opt/images
      - ./client/build:/opt/client
    ports:
      - "${NGINX_PORT}:443"

  server:
    build: ./server
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./server:/opt/server
      - ./.volumes/images:/opt/images
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SERVER_URL: "https://${NGINX_HOST}/api"
      IMAGES_URL: "https://${NGINX_HOST}/images"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      IMAGES_DIR: "/opt/images"

  client:
    build: ./client
    working_dir: /opt/client
    volumes:
      - ./client:/opt/client
    environment:
      REACT_APP_SERVER_URL: "https://${NGINX_HOST}/api"
    command: yarn build

  db:
    image: postgres:15
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
