version: "3.9"
services:
  router:
    build: ./router
    ports:
      - 3000:443
    depends_on:
      - client
      - server

  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/zera-draws
    depends_on:
      - db

  client:
    build: ./client
    command: bash -c "yarn start"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
