version: "3.9"

services:
  server:
    environment:
      RAILS_ENV: development
      SERVER_URL: http://${HOSTNAME}:${SERVER_PORT}
      IMAGES_URL: http://${HOSTNAME}:${IMAGES_PORT}
    ports:
      - "${SERVER_PORT}:3000"

  client:
    volumes:
      - ./.volumes/router/ssl:/opt/ssl
    environment:
      REACT_APP_SERVER_URL: http://${HOSTNAME}:${SERVER_PORT}
    command: yarn start
    ports:
      - "${CLIENT_PORT}:3000"

  db:
    ports:
      - "${DB_PORT}:5432"

  images:
    image: halverneus/static-file-server:latest
    volumes:
      - ./.volumes/images:/web
    ports:
      - "${IMAGES_PORT}:8080"
