volumes:
  vol-database:
  vol-images:
  vol-client:

services:
  router:
    extends:
      file: docker-compose.shared.yml
      service: router
    ports:
      - "${APP_PORT}:80"
      - "${DEV_SERVER_PORT}:443"

  server:
    extends:
      file: docker-compose.shared.yml
      service: server
    volumes:
      - ./server:/opt/server:rw
      - vol-images:/opt/images:rw
    environment:
      CLIENT_URL: "${DEV_CLIENT_URL}"
      SERVER_URL: "${DEV_SERVER_URL}/api"
      IMAGES_URL: "${DEV_SERVER_URL}/images"

  client:
    extends:
      file: docker-compose.shared.yml
      service: client
    volumes:
      - ./client:/opt/client:rw
      - ./router/ssl:/opt/ssl:ro
      - vol-client:/opt/client/build:rw
    environment:
      HTTPS: true
      SSL_CRT_FILE: /opt/ssl/current.crt
      SSL_KEY_FILE: /opt/ssl/current.key
      REACT_APP_SERVER_URL: "${DEV_SERVER_URL}/api"
    command: yarn start
    ports:
      - "${DEV_CLIENT_PORT}:3000"

  og-injector:
    extends:
      file: docker-compose.shared.yml
      service: og-injector
    volumes:
      - ./og-injector:/opt/og-injector:rw
      - vol-client:/opt/client:ro
    command: yarn watch

  db:
    extends:
      file: docker-compose.shared.yml
      service: db
    ports:
      - "${DEV_DB_PORT}:5432"
