version: "3.9"

services:
  server:
    volumes:
      - ./server:/opt/server
    environment:
      RAILS_ENV: development
      CLIENT_URL: "https://${HOSTNAME}:${CLIENT_PORT}"

  client:
    volumes:
      - ./client:/opt/client
      - ./.volumes/ssl:/opt/ssl
    environment:
      HTTPS: true
      SSL_CRT_FILE: /opt/ssl/current.crt
      SSL_KEY_FILE: /opt/ssl/current.key
      REACT_APP_ENV: development
    command: yarn start
    ports:
      - "${CLIENT_PORT}:3000"

  og-injector:
    volumes:
      - ./og-injector:/opt/og-injector
    command: yarn watch
    ports:
      - "${INJECTOR_PORT}:3000"
    environment:
      CLIENT_URL: "https://${HOSTNAME}:${CLIENT_PORT}"

  db:
    ports:
      - "${DB_PORT}:5432"
