services:
  router:
    build: ./router
    ports:
      - 80:80
      - 443:443
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/zera-draws
    depends_on:
      - db
      - router
  client:
    build: ./client
    command: bash -c "yarn start"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - server
      - router
    volumes:
      - ./client:/usr/src/app
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
