source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'rails', '~> 6.1.3', '>= 6.1.3.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bcrypt'
gem 'jwt'
gem 'whenever', require: false
gem 'csv'

gem 'fastimage'
gem "mini_magick"

gem 'dotenv-rails'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails', '~> 5.0.0'

  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false

  gem 'net-smtp'
end

group :development do
  gem 'annotate'
  gem 'listen', '~> 3.3'
  gem 'spring'
end
