[package]
name = "og-injector-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-server = { version = "0.6", features = ["tls-rustls"] }
tracing-subscriber = "0.3.18"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tracing = "0.1.40"
dotenv = "0.15.0"
serde_json = "1.0"
serde = { version = "1.0.204", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["json"] }
url_serde = "0.2.0"
url = "1.7.2"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
iso8601 = "0.6.1"
derive_builder = "0.20.0"
mime_guess = "2.0.5"
mime = "0.3.17"

[profile.release]
panic = "abort"
