name: Deploy - Prod
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Run remote script
        uses: appleboy/ssh-action@v1.0.3
        env:
          DEPLOY_SHA: ${{ github.sha }}
        with:
          host: zeragamba.art
          port: 22
          username: zeradraws
          key: ${{ secrets.DEPLOY_KEY }}
          envs: DEPLOY_SHA
          script_stop: true
          script: |
            cd /opt/apps/staging.zeragamba.art
            git fetch
            git checkout $DEPLOY_SHA
            ./deploy.sh
