name: Deploy - Prod
on:
  push:
    branches:
      - stable
jobs:
  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run remote script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: zeragamba.art
          port: 22
          username: zeradraws
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            cd /opt/apps/zeragamba.art
            git pull
            ./deploy.sh
